# Use official Python image as base
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt ./
RUN pip install -r requirements.txt

# Copy application code
COPY ..

# Expose port
EXPOSE 5000

# Run the Flask app
CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0"]
